name: bsr
description: Brainslug Reader
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  archive: ^3.4.6
  async: ^2.11.0
  collection: ^1.17.2
  convert: ^3.1.1
  crypto: ^3.0.3
  encrypted_storage:
    path: packages/encrypted_storage
  epubx:
    git:
      url: https://github.com/nesquikm/epubx.dart.git
      ref: dev
  fancy_logger:
    path: packages/fancy_logger
  fb2_parse:
    git:
      url: https://github.com/nesquikm/fb2_parse.git
      ref: main
  file_picker: ^6.0.0
  flutter:
    sdk: flutter
  flutter_html:
    git:
      url: git@github.com:nesquikm/flutter_html.git
      ref: 4f8d2a89ef44f2e5629b0955872a28b0afabe51a
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  freezed_annotation: ^2.4.1
  go_router: ^12.0.0
  html: ^0.15.4
  image: ^3.3.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  mockito: ^5.4.2
  path: ^1.8.3
  path_provider: ^2.1.1
  riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  scrollable_positioned_list: ^0.3.8
  test: ^1.24.3
  xml: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.4
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  io: ^1.0.4
  json_serializable: ^6.7.1
  melos: ^3.1.1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
