name: bsr
description: Brainslug Reader
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  archive: ^3.4.6
  async: ^2.11.0
  bloc: ^8.1.2
  convert: ^3.1.1
  crypto: ^3.0.3
  epubx:
    path: ../epubx.dart
  fb2_parse:
    path: ../fb2_parse
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  freezed_annotation: ^2.4.1
  image: ^3.3.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  riverpod_annotation: ^2.2.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
